import { Inter } from 'next/font/google'
import './style/globals.scss'
import './style/header.scss'
import './style/footer.scss'
import Header from './Header'
import { getServerSession } from 'next-auth'
import { authOptions } from '@/pages/api/auth/[...nextauth]'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  let session = await getServerSession(authOptions)
  console.log(session);
  
  return (
    <html lang="ko">
      <body className={inter.className}>
        <Header session={session}></Header>
        {children}

        <div className='footer'>
          <div className='left'>&copy;CarrotMarket All reserve.</div>
          <div className='right'>Tel 010.1234.5678</div>
        </div>
        </body>
    </html>
  )
}
